export HOME=/home/tashima
export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH=$HOME/.oh-my-zsh
export PKG_CONFIG_PATH=/usr/lib/pkgconfig

ZSH_THEME="robbyrussell"
plugins=(git alias-tips zsh-completions almostontop zsh-autosuggestions pip )
plugins+=(history history-substring-search sudo)
plugins+=(node npm z mosh k zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

## ALIAS
alias c="clear"
alias ez="nvim $HOME/.zshrc"
alias server="python -m SimpleHTTPServer"
alias socks="ssh -vND 8888 kim"
alias ls='ls -a --color=auto'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano -w PKGBUILD'
alias more=less
alias e=espanso
alias es="espanso stop"
alias eS="espanso start"
alias er="espanso restart"
alias u="upower -i /org/freedesktop/UPower/devices/battery_BAT0"
# change keyboard layout
alias br='setxkbmap br'
alias us='setxkbmap us'

# default editor
export EDITOR=vim
export VISUAL="$EDITOR"

## GIT
GIT_AUTHOR_NAME="Pedro Tashima"
GIT_COMMITTER_NAME="$GIT_AUTHOR_NAME"
git config --global user.name "$GIT_AUTHOR_NAME"
GIT_AUTHOR_EMAIL="pedrotashima42@gmail.com"
GIT_COMMITTER_EMAIL="$GIT_AUTHOR_EMAIL"
git config --global user.email "$GIT_AUTHOR_EMAIL"

## NPM
npm set init.author.email "pedrotashima42@gmail.com"
npm set init.author.name "tashima42"
npm set init.license "MIT"

##### EXPORT 

## JAVA / CLOJURE
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64/bin/java
export M2=$HOME/.m2
export PATH=$PATH:$M2

## GO
#export GOPATH=$HOME/code/golang
#export PATH=$GOPATH/bin:$PATH

# Make zsh know about hosts already accessed by SSH
zstyle -e ':completion:*:(ssh|scp|sftp|rsh|rsync):hosts' hosts 'reply=(${=${${(f)"$(cat {/etc/ssh_,~/.ssh/known_}hosts(|2)(N) /dev/null)"}%%[# ]*}//,/ })'

## CUSTOM FUNCTIONS

# Create a new directory and enter it
function mkd() {
	mkdir -p "$@" && cd "$_";
}

# # ex - archive extractor
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;; *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
