#!/bin/sh
# update & upgrade #
echo "Updating and upgrading"
sudo apt-get update
sudo apt-get upgrade

clear 

echo "Adding PPAs"
# GIT PPA
sudo add-apt-repository ppa:git-core/ppa
clear 

echo "Updating"
sudo apt update

clear 

echo "Installing snap, git, virtualbox, mongodb, vlc, vscode, discord, chrome"
# install snap, git 
sudo apt install snapd
sudo apt install virtualbox
sudo apt install git
sudo apt install -y mongodb
sudo apt install docker-compose

sudo snap install vlc
sudo snap install code --classic
sudo snap install discord 
sudo snap install docker

wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo apt install ./google-chrome-stable_current_amd64.deb

clear 

echo "Installing nvm, node, npm, yarn, vue/cli, docker"
# nvm install
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
nvm 
nvm install 14.7.0

# npm & yarn install
sudo apt install npm
sudo npm install -g yarn

# Vue install
sudo yarn global add @vue/cli
sudo yarn global add commitizen


#fix snap not showing apps on drawer
mkdir -p ~/.config/environment.d
echo "PATH=$PATH:/snap/bin\nXDG_DATA_DIRS=\"${XDG_DATA_DIRS:-/usr/local/share:/usr/share}:/var/lib/snapd/desktop\"" > ~/.config/environment.d/60-snap-icons-and-bin.conf
