#!/bin/sh
# update & upgrade #
echo "Updating and upgrading"
sudo apt-get update
sudo apt-get upgrade

clear 

echo "Adding PPAs"
# GIT PPA
sudo add-apt-repository ppa:git-core/ppa
sudo add-apt-repository ppa:mattrose/terminator
clear 

echo "Updating"
sudo apt update

clear 

echo "Installing snap, git, virtualbox, mongodb, docker-compose, falmeshot, gnome-tweaks, vlc, vscode, discord, docker, barrier, chrome"
# install snap, git 
sudo apt install -y snapd
sudo apt install -y git
#sudo apt install -y virtualbox
#sudo apt install -y mongodb
sudo apt install -y docker-compose
sudo apt install -y terminator
#sudo apt install -y gnome-tweaks

sudo snap install code --classic
#sudo snap install discord 
sudo snap install docker
#sudo snap install barrier
sudo snap install firefox
sudo snap install flameshot
sudo snap install termius-app
sudo snap install nvim --classic
sudo snap install brave

clear 

echo "Installing nvm, node, npm, yarn, vue/cli, commitizen"
# nvm install
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
nvm 
nvm install 14

# npm & yarn install
sudo apt install npm
sudo npm install -g yarn

# Install Zsh
sudo apt install -y zsh
sudo sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
chsh -s $(which zsh)

#fix snap not showing apps on drawer
#mkdir -p ~/.config/environment.d
#echo "PATH=$PATH:/snap/bin\nXDG_DATA_DIRS=\"${XDG_DATA_DIRS:-/usr/local/share:/usr/share}:/var/lib/snapd/desktop\"" > ~/.config/environment.d/60-snap-icons-and-bin.conf
